---

services:
  converter:
    image: draikx21/h265-converter
    restart: unless-stopped
    environment:
      UID: 1000
      GID: 1000
      BATCH: 0
      DEBUG: "False"
      DELETE: "False"
      TZ: "UTC"
    volumes:
      - mnt:/mnt
