---

services:
  converter:
    image: draikx21/h265-converter
    restart: unless-stopped
    user: 1000:1000
    environment:
      BATCH: 0
      DEBUG: "False"
      DELETE: "False"
      TZ: "UTC"
    volumes:
      - mnt:/mnt
