---

services:
  converter:
    image: draikx21/h265-converter
    restart: unless-stopped
    user: 1000:1000
    environment:
      BATCH: 0
      CONVERT: "True"
      DEBUG: "False"
      DELETE: "False"
      PERSIST: "False"
      RETRY_FAILED: "False"
      TZ: "UTC"
    volumes:
      - data:/tmp
      - /mnt:/mnt
volumes:
  data:
